### ISSUE TITLE
[CCLS] Need help to understand how the plugin communicates with the language server 

### ISSUE THREAD

**Issue by nicolnt** [jackguo380/vim-lsp-cxx-highlight#16]
**Describe the bug**
Hi, I'm a little confused about how the plugin manages to receive highlighting information from the language server. As I have experienced and according to what I understand in the VimDoc help for vim-lsp-cxx-highlight, it seems to be able go get information back only when the current state of the file is written onto disk. So it's unable to display full highlighting on a group while being tipped. 
According to *LspCxxHighlight* section.
"Redo highlighting for the current buffer. This only reapplies highlighting
using the locally cached data. There is currently no way to force the language
server to resend highlighting data." 
So I enabled swapfile to create this "locally cached data" automatically, but it doesn't work for me.
Can I get some help to understand LSP syntax highlighting pipeline please? And to guide me towards a solution if there's any :smiley_cat: 

**To Reproduce**
- Enable swapfile
- Write some Cxx file and do not write it manually with `:w`
- Trigger `:LspCxxHighlight`

**Expected behavior**
I was expecting to get some syntax highlighting on the group I just tipped in my file.

**Screenshots**
![Screenshot_20191228_123707](https://user-images.githubusercontent.com/12377588/71543064-c8c95300-296e-11ea-80e7-5030e2507cb9.png)

**Configuration (Fill this out):**
 - NVIM v0.5.0-nightly
 - Output of `ccls --version` 
```
ccls version <unknown>
clang version 8.0.1-3build1 (tags/RELEASE_801/final)
```
 - Parts of my `init.vim` 
```vim
set swapfile
let g:lsp_cxx_hl_use_nvim_text_props = 1
let g:lsp_cxx_hl_use_text_props = 1
```

**Log File:**
Contents of the log file (there's nothing before `:LspCxxHighlight`):

```vim
Sat 28 Dec 2019 12:33:54 PM CET: hl_symbols (textprop nvim) highlighted 111 symbols in file RBF.cpp
Sat 28 Dec 2019 12:33:54 PM CET: operation hl_symbols (textprop nvim) RBF.cpp took   0.010580s to complete
Sat 28 Dec 2019 12:33:54 PM CET: hl_skipped (textprop nvim) highlighted 0 skipped preprocessor regions in file RBF.cpp
Sat 28 Dec 2019 12:33:54 PM CET: operation hl_skipped (textprop nvim) RBF.cpp took   0.000075s to complete

```
Please excuse me if this is not the right way to fill an issue, it's the first time I'm doing it. Don't hesitate to correct me if I'm wrong.
Thanking you in advance, I really enjoy the plugin for now, it's just the non-automatic highlighting that is not so convenient !

**Comment by jackguo380** [comment]
Hi nicolnt,

I am not entirely sure what your issue is but from your reproduction steps it sounds like it may be related to #4. If this is the case then this isn't really considered a bug, its more related to the behavior of ccls.

Essentially how this plugin works is that ccls will send a `$ccls/publishSemanticHighlight` notification every time the buffer is saved (Written to disk) in the editor. Your LSP client will then receive the notification and pass it along to this plugin which parses the JSON and adds the appropriate highlighting in the buffer.

I suspect what you are running into here is that the buffer does not get updated with highlighting when you simply write new lines without saving it. As noted before ccls (and cquery) only updates the highlighting upon a save to disk. The main reason is probably that the parsing of the highlighting and re-applying it took too much time and couldn't be done incrementally.

There isn't really a fix/workaround that this plugin can do to change the behavior. A possibility is to change ccls to update highlighting after a few seconds of inactivity, however that's more of a issue for ccls than this plugin.

**Comment by nicolnt** [comment]
@jackguo380 you are totally right as I don't think it's a bug too. I could not find a way to ask questions publicly without filling an issue 😉
The reason why I asked is because I saw this in the plugin help *LspCxxHighlight* section.
> "Redo highlighting for the current buffer. This only reapplies highlighting
using the locally cached data. There is currently no way to force the language
server to resend highlighting data."

It seemed to me that local cache is a different thing than the actual file, I thought the help was referring to the vim swapfiles. 
Can you clarify this please? Is it actually referring to the previously received JSON data from ccls API? If it is I understand my mistake, and why it would not update newly inserted code!
Thanks for your reply by the way.

**Comment by jackguo380** [comment]
Ah sorry I forgot to address that point, the cached data has nothing to do with swapfiles. As you said it refers to the JSON data from ccls.

For reference this is what the JSON data would look like for a simple hello world:
```cpp
#include <iostream>

int main(void) {
    std::cout << "Hello World" << std::endl;

    return 0;
}
```

```json
{"jsonrpc":"2.0","method":"$ccls/publishSemanticHighlight","params":{"uri":"file:///tmp/test.cpp","symbols":[{"id":0,"parentKind":0,"kind":3,"storage":0,"ranges":[],"lsRanges":[{"start":{"line":3,"character":4},"end":{"line":3,"character":7}},{"start":{"line":3,"character":34},"end":{"line":3,"character":37}}]},{"id":2,"parentKind":3,"kind":12,"storage":0,"ranges":[],"lsRanges":[{"start":{"line":3,"character":39},"end":{"line":3,"character":43}}]},{"id":1,"parentKind":1,"kind":12,"storage":0,"ranges":[],"lsRanges":[{"start":{"line":2,"character":4},"end":{"line":2,"character":8}}]},{"id":0,"parentKind":0,"kind":13,"storage":1,"ranges":[],"lsRanges":[{"start":{"line":3,"character":9},"end":{"line":3,"character":13}}]}]}}
```

You can view the parsed version of this data using:
```vim
echo b:lsp_cxx_hl_symbols     " The Raw Data
" or
LspCxxHlDumpSyms              " Slightly prettier output
```

When you run `:LspCxxHighlight` it simply reapplies the cached data to the buffer, no new highlighting data is received from ccls. Since the cached data is the same as from the previous saved version of this file on disk any changes you made since then will not have any highlighting on it.

**Comment by nicolnt** [comment]
Thanks heaps for all this clarification!
And many thanks for maintaining the project too, it's been a lot easier for me to code in CPP, especially for OpenGL as I can quickly recognize all the built-in macros 😄
