### ISSUE TITLE
Semantic highlighting works only when there isn't a file argument.

### ISSUE THREAD

**Issue by iamtsac** [jackguo380/vim-lsp-cxx-highlight#24]
I am using the plugin with coc.nvim and ccls and since today when I open a C file as an argument the highlighting doesn't work, even though the CocInfo says "refresh semantic highlighting".  If I just open Neovim and find the file using coc-explorer the highlighting is applied. That's really weird.  I also tried to see if it works with the a C++ but it happens with C++ too. The first screenshot is when I open the file as an argument and the second when I open it through the explorer.

![without](https://user-images.githubusercontent.com/39421505/80895270-9304f400-8ceb-11ea-8307-8610d43b97e5.png)

![with](https://user-images.githubusercontent.com/39421505/80895301-f4c55e00-8ceb-11ea-8cfd-889d3642e68e.png)

**The coc-settings for the language server**

![image](https://user-images.githubusercontent.com/39421505/80895310-31915500-8cec-11ea-8af9-6bdb9067ae0c.png)

This is what I got in the log when I open the file as an argument.

```
**Sun 03 May 2020 03:16:15 AM EEST: operation hl_symbols (textprop nvim) CEID/Parallel/serial.c took   0.000043s to complete
Sun 03 May 2020 03:16:15 AM EEST: operation hl_skipped (textprop nvim) CEID/Parallel/serial.c took   0.000030s to complete**
```

**Comment by jackguo380** [comment]
Hi iamtsac,

I was unable to reproduce this with my local setup using vim or nvim and the latest coc.nvim.

I can't help but notice that your airline is showing different filenames on your two screenshots. On the first one where you open the file as a argument to vim the path is `CEID/Parallel/serial.c` and on your second one where you open using coc-explorer it is `serial.c`. This implies that vim has a different working directory based on the way you opened the file.

Note that ccls expects a `compile_commands.json` or `.ccls` file in the working directory. If this is not found sometimes ccls fails to compile your source code and thus cannot produce valid highlighting information. Based on your logs posted this seems like a possible senario since the amount of time it took to highlight is far too low (Usually it is around ~50-100ms). So vim-lsp-cxx-highlight is receiving notifications correctly but nothing is inside the notifications.

I recommend adding something to your vimrc to change to the correct directory when opening a file. For example [this is from my vimrc](https://github.com/jackguo380/.vim/blob/95e1d2ec97852c40a8a6827cc064eafc229bb3ff/vimrcs/start.vim#L3-L38).

**Comment by iamtsac** [comment]
It was the .ccls file that caused this situation. Thank you!
