### ISSUE TITLE
Support for other LSP plugins

### ISSUE THREAD

**Issue by Shatur95** [jackguo380/vim-lsp-cxx-highlight#25]
Thank you for the plugin! Is it possible to integrate with other LSP plugins? For example, I recently switched to [vim-lamp](https://github.com/hrsh7th/vim-lamp). Can I somehow configure it to make it work with your plugin?

**Comment by jackguo380** [comment]
Hi Shatur95,

I had a look into vim-lamp and it looks like it doesn't provide any method for a third party plugin to receive notifications as [seen here](https://github.com/hrsh7th/vim-lamp/blob/5749e4b4a0c28381721ead5a40020c1fd0af9825/autoload/lamp/server/notification.vim#L32).

In order for vim-lsp-cxx-highlight to work vim-lamp will need to provide some kind of API, could you open a issue on vim-lamp to request this functionality and tag me?

For example the API used to register for notifications on vim-lsp is [this](https://github.com/jackguo380/vim-lsp-cxx-highlight/blob/724379406daafb494d5e7bb9548f809139d44a09/autoload/lsp_cxx_hl/client/vim_lsp.vim#L4-L5), and on LanguageClient-neovim it is [this](https://github.com/jackguo380/vim-lsp-cxx-highlight/blob/724379406daafb494d5e7bb9548f809139d44a09/autoload/lsp_cxx_hl/client/LanguageClient.vim#L14-L23).

**Comment by Shatur95** [comment]
Thanks for explanations! I trying to get semantic highlighting from Clang. If I understand correctly, there is `sementicHighlights` (unofficial spec) and `semanticTokens` (official candidate). `vim-lamp` have plans to implement the last one (`semanticTokens` support was added recently to clangd: https://github.com/llvm/llvm-project/commit/71177ac16801ceced4b7dcdd21b05345416f31df#diff-bc83abf3e556418f438c09a672856449). Is this plugin trying to provide `semanticHighlights`? So, is `vim-lamp` need to have additional support to make your plugin to work?

**Comment by jackguo380** [comment]
This plugin implements neither of those two proposed standards. The primary purpose of this plugin is to provide semantic highlighting for `cquery` and `ccls`. Both of these language servers implement non-standard protocols for semantic highlighting.

`clangd` support was later added for people using `coc.nvim` by `coc-clangd`. Note that it is actually `coc-clangd` which implements the old proposed standard for semantic highlighting and converts it to stuff `vim-lsp-cxx-highlight` understands. As a result vim-lsp-cxx-highlight won't work with clangd unless `coc.nvim` and `coc-clangd` are in the middle to do this conversion.

Essentially if `vim-lamp` wants to use `vim-lsp-cxx-highlight` as its highlighting backend then `vim-lamp` needs to perform the conversion of clangd's messages and then call the right functions in `vim-lsp-cxx-highlight`. This is actually quite non-trivial to do in vimscript due to the fact that the old standard uses binary encoded data in its messages. There would be a lot of work for `vim-lamp` to implement a standard which is already going out the door and as far as I know is only implemented by `clangd` and `eclipse.jdt.ls`. Probably best to wait for semanticTokens to land in clangd, I'm assuming it might be ready by LLVM 11 or 12.

**Comment by Shatur95** [comment]
Thank you a lot for explanations!
Will wait for `semanticTokens` :)
