### ISSUE TITLE
Having problem with installation on Windows 10

### ISSUE THREAD

**Issue by ashrasmun** [jackguo380/vim-lsp-cxx-highlight#26]
Hey,

I have quite a big problem with installation of this plugin, but it looks fantastic, so I keep pressing on. I'm on Windows, using Vim 8.1.

I installed:
`prabirtshrestha/async.vim`
`prabirtshrestha/vim-lsp`
`jackguo380/vim-lsp-cxx-highlight`
Nothing much to say here

`cquery` using the documentation here; https://github.com/cquery-project/cquery/wiki/Building-cquery . I made sure to install it properly on Windows, but I couldn't start the lsp server - I just don't know how to do it. I copy pasted the code from https://github.com/jackguo380/vim-lsp-cxx-highlight/blob/master/sample-configs/vim-lsp-register.vim into my `.vimrc`, but nothing was happening and `echo executable('cquery')` returned 0 at all times. I read somewhere, that `cquery` is not maintained anymore, so I wanted to try different approach.

I installed:
nodejs
'neoclide/coc.nvim'
'clangd/coc-clangd'
I went to `vim-lsp-cxx-highlight/sample-configs/coc-settings.json` and pasted the code from this project's main page.

    {
        "clangd.semanticHighlighting": true
    }

I just... don't know what to do here. There's thousand of different things to install and I got super confused :( I think that at least coc works, because I get some code completion out of it, but I cannot get the rest of the stuff to work. Can you help me please?

**Comment by jackguo380** [comment]
Hi ashrasmun,

Just to clarify a few things first. The configurations problems you are having a mainly to do with your LSP client (`vim-lsp` or `coc.nvim`) not with vim-lsp-cxx-highlight. Normally you should file a issue with those projects instead.

You are right about `cquery` not being maintained, it has been like that for over a year. However it should still "work" as long as you are willing to stick wtih LLVM 6 or lower and lose support for more modern C++ standards. `ccls` is generally a more reliable server thats actually maintained, only caveat being that it is slightly harder to build since it doesn't support auto-downloading LLVM.

For `coc.nvim` make sure you are installing `coc-clangd` using the vim command `:CocInstall coc-clangd` do **not** use your package manager. `coc.nvim` extensions are not vim plugins but rather plugins to `coc.nvim` directly. After you install `coc-clangd` on the github page it says you can run `:CocCommand clangd.install` to install the `clangd` executable automatically. **Disclaimer:** I never used this command since I install clangd myself, nor do I know if it works on Windows.

If this is still not working you should refer to these pages:
https://github.com/neoclide/coc.nvim/wiki/Using-coc-extensions#manage-coc-extensions
https://github.com/clangd/coc-clangd

**Comment by ashrasmun** [comment]
Thank you very much for guidance! I will try to proceed with these tips :) Have a nice one!

**Comment by ashrasmun** [comment]
Ok, I managed to make it work - it's fantastic!
I had to install `clangd` manually using the link provided via `:messages` (https://clangd.llvm.org/installation.html). When it comes to integration with `coc.nvim`, `:CocInstall coc-clangd` was enough in my case, but I also had to remove `Plug 'clangd/coc-clangd'` from the plugin list. 

Then, I needed to run `:CocConfig` and paste the configuration you mentioned on the main page. https://github.com/neoclide/coc.nvim/wiki/Using-the-configuration-file site was very helpful too.

Aaaand, now it works! Thanks a lot for your work :)
![image](https://user-images.githubusercontent.com/12000269/81442867-afce7b00-9174-11ea-9058-2a8a0c85ae6c.png)
