### ISSUE TITLE
Change begin/end of skipped region

### ISSUE THREAD

**Issue by phush0** [jackguo380/vim-lsp-cxx-highlight#30]
This is not a bug, more question.
I am trying to change coloring of begin/end of skipped regions. I know that there is LspCxxHlSkippedRegionBeginEnd which currently is set to group Normal. I am trying to set it to comment, so skipped region begin and end is same as skipped region. But some how always revert to default:
I have tried:
```
hi default link LspCxxHlSkippedRegionBeginEnd Comment
```

nothing happened.
Tried to set Group name in colorscheme to be exact same as comment, nothing again. Did I have to change priority to work correct ?

edit:
looking at code it is impossible for neovim using textprop, because function will auto skip indexes for begin end. Also something very interesting. For textprop, priority is not working too, so it will color all  document symbols and then all skipped ranges.

**Comment by jackguo380** [comment]
Unfortunately it is a bug, that highlight group only really works for the `matchaddpos` based highlighting (which is only used for old versions of vim/neovim). I was hoping that the default behavior of the other backends would be fine for pretty much everyone and that would not have to be changed. The main reason it is not implemented is because of inconsisent behavior between the APIs which made it hard to add.

The same goes for the priority since that is a concept only exists for `matchaddpos` or vim textprop. Neovim's `nvim_buf_add_highlight` which is used by default for current versions of neovim doesn't support any kind of priority.

I'll update the docs to reflect this.

**Comment by phush0** [comment]
Thank you for answer, I will close this for now.
