### ISSUE TITLE
Highlight only works on saved buffers

### ISSUE THREAD

**Issue by hlbstd** [jackguo380/vim-lsp-cxx-highlight#4]
Title is pretty self-explanatory. The highlight does not work on unsaved text, launching LspCxxHighlight manually does not colorize the text written since the last save. It seems to highlight the current characters based on the symbols present on the disk.
For instance, if I write: `struct test{};` I have to save to get `test` highlighted as a type. Moreover, if I replace the line with anything, the highlight will be kept but according to the character present on the saved buffer: `struct testtest{};` will see only the first text highlighted, and `struct tes{};` will see the first bracket highlighted as if it were a type.

**Comment by jackguo380** [comment]
This is mostly due to how ccls/cquery implement the semantic highlighting. From some basic testing using vim-lsp + ccls it seems `textDocument/didChange` (Sent after exiting insert mode) does not trigger semantic highlighting to be resent whereas `textDocument/didSave` (Sent after writing to disk) does. This is likely a optimization on ccls' end to prevent semantic highlighting from being sent too often. I think this is reasonable given how much data is in each semantic highlighting notification.

Without ccls sending the data over there's not much vim-lsp-cxx-highlight can do about the semantic highlighting mismatching the text. Vim does not offer any API to allow match groups to move with the text, so it is expected that if you change the text it will have broken highlighting until you save. There probably are ways you can do intelligent updating while editing but these algorithms would too computationally intensive to implement in vimscript.

If you do want the semantic highlighting to be sent more often (E.g. after exiting insert mode), you can post a issue on ccls asking for a initializationOption to change this behavior.

**Comment by hlbstd** [comment]
I figured that since the rest of ccls features worked on text changed semantic highlighting should too, thanks for correcting my mistake.
I think I'll have a look around ccls source code to see what can be done.

**Comment by bfrg** [comment]
@jackguo380 There is a way to have highlighting groups move with the text. See `:h text-properties`. The feature is still under development and there are some known [bugs](https://github.com/vim/vim/issues/3912), but apart from that issue it seems to work.

**Comment by jackguo380** [comment]
@bfrg thats awesome, didn't know vim had something like this in the works. I just had a look at the docs for it and it seems to be exactly what vim-lsp-cxx-highlight (and color_coded) needs.

**Comment by jackguo380** [comment]
Closing this since I implemented support for both vim8.1 `+textprop` and neovim's equivalent highlight APIs (See #12). I tested on a reasonably new vim and textprop seems fairly usable.

```sh
$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 30 2019 00:10:35)
```

If you see any problems please open a new issue.
