### ISSUE TITLE
Feature request: annotations

### ISSUE THREAD

**Issue by Falkgaard** [jackguo380/vim-lsp-cxx-highlight#57]
Hi, I use a lot of annotations such as [[nodiscard]], [[maybe_unused]], [[likely]], [[fallthrough]], etc. However, this plugin doesn't appear to provide any highlighting for these. Would it be possible to have that implemented as feature..?

Other than that I love the plugin, great work!

Regards,
-Falkgaard

-----

**EDIT:**

I added `syntax match Annotation /\[\[\w\+\]\]/` to `~/.config/nvim/after/syntax/cpp.vim` and then a highlight rule for Annotation to get it highlighted on my end.

**Comment by jackguo380** [comment]
Highlighting attributes is actually very easy to implement in vim's own syntax highlighting because they don't require any compiler analysis unlike disguishing a variable from a macro or function. Also, ccls does not actually send any data for attributes so I can't really implement it in vim-lsp-cxx-highlight.

I usually recommend people use a "c++ syntax extension pack" like [bfrg/vim-cpp-modern](https://github.com/bfrg/vim-cpp-modern) in addition since vim's included c++ syntax file is constantly out of date/incomplete. That plugin will highlight attributes if you set `g:cpp_attributes_highlight = 1`.

Alternatively, if you don't want that full plugin you can copy-paste the [lines for attributes](https://github.com/bfrg/vim-cpp-modern/blob/1a0d31ff541e115895b6357b203a0969835b3212/after/syntax/cpp.vim#L15-L17). IMO the use of the `Identifier` highlight group for the brackets is kind of weird, but you can always remap it to something else.

**Comment by Falkgaard** [comment]
Alright, fair enough! 

Cheers for the speedy and helpful resolution.
