### ISSUE TITLE
Does it support termux on Android using clangd?

### ISSUE THREAD

**Issue by YaQia** [jackguo380/vim-lsp-cxx-highlight#81]
**Describe the bug**
I found it seemed not available on termux for Cpp highlighting. The classes and functions are not highlighted.

**To Reproduce**
> the commands below are termux commands.

pkg install neovim
pkg install clangd
Install coc.nvim by setting init.vim
Install coc-clangd
Install vim-lsp-cxx-highlight
In vim, typing :CocConfig to set like the example.

**Expected behavior**
highlighting vscode-like with cmake projects.

**Screenshots**

**Configuration (Fill this out):**
 - Neovim 0.6.0
 - Clangd 13.0.0
 - Parts of your `vimrc` or `init.vim` that you think are relevant to vim-lsp-cxx-highlight
```vim
Plug 'neoclide/coc.nvim', {'branch': 'master', 'do': 'yarn install --frozen-lockfile'} 
" I use the release branch until I found this bug...
Plug 'jackguo380/vim-lsp-cxx-highlight'
Plug 'octol/vim-cpp-enhanced-highlight'
```
**Log File:**
Enable logging by adding these lines:
```vim
let g:lsp_cxx_hl_log_file = '/tmp/lsp-cxx-hl.log'
let g:lsp_cxx_hl_verbose_log = 1
```
Then post the contents of the log file:

```vim
Wed Dec 15 13:14:39 2021: lsp_cxx_hl beginning initialization ...
Wed Dec 15 13:14:39 2021: vim-lsp not detected
Wed Dec 15 13:14:39 2021: LanguageClient-neovim not detected
Wed Dec 15 13:14:39 2021: coc.nvim successfully registered
Wed Dec 15 13:14:39 2021: nvim-lsp successfully registered
```

**Additional context**
All the same configurations work well on my x86-64 Ubuntu20.04, so I wanna know whether it is not supported on Android yet.

**Comment by YaQia** [comment]
BTW, my Ubuntu20.04 neovim version is 0.4.3, I guess it's because 0.4.3 doesn't support nvim-lsp?

**Comment by YaQia** [comment]
I've tried to use nvim-lsp, but it still doesn't work. I removed coc-clangd, but it's not working...

**Comment by YaQia** [comment]
I've tried to use vim, not working...

**Comment by jackguo380** [comment]
I'm not too familiar with the differences in versions of neovim, while I do use neovim daily I am mostly compiling it from source.

There's nothing preventing this plugin specifically from running on any architecture that can run vim/neovim as it is written 100% in vimscript.

As a first step please look more into if coc.nvim is working correctly on your Android setup. Clangd support in this plugin **requires** coc.nvim, because coc translates clangd's different highlighting protocol back to something this plugin can understand. Whether nvim-lsp works or not is likely not making any difference in this case.

Also check if you have the correct coc configuration flags. From the README:
```json
{
    "clangd.semanticHighlighting": true,
    "coc.preferences.semanticTokensHighlights": false
}
```

**Comment by YaQia** [comment]
Thanks! Maybe I have some configuration neglected, I'll check the coc.nvim configuration.
